ARG ELIXIR_VERSION=1.18.3
FROM elixir:${ELIXIR_VERSION} AS base

WORKDIR /app

ENV MIX_ENV="test"
ENV LANG="en_US.UTF-8"
ENV LANGUAGE="en_US:en"
ENV LC_ALL="en_US.UTF-8"

RUN apt-get update -y && apt-get install -y build-essential git libstdc++6 openssl libncurses5 locales ca-certificates
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

RUN mix local.hex --force && \
    mix local.rebar --force

COPY mix.exs mix.lock ./
COPY vendor ./vendor
RUN mix deps.get && mkdir config

COPY .buildkite/scripts/build.sh config/config.exs config/test.exs config/
RUN ./config/build.sh && mix deps.compile

COPY . .
RUN mix assets.setup && mix assets.build && mix compile
