services:
  episodical:
    container_name: episodical
    environment:
      HOSTNAME: 'localhost'
      PORT: '8088'
      DATA_FILE: '/data/episodical.db'
      DATA_PASSPHRASE: 'Some_Type_0F_Phra5e!'
    volumes:
      - '/tmp/episodical/:/data/:rw'
    build:
      context: .
      dockerfile: './Dockerfile'
    ports:
      - '8088:8088'
    networks:
      - episodical

networks:
  episodical:
    name: episodical

