agents:
  queue: linux-with-base

steps:
  - label: ":elixir: build"
    key: build
    command: |
      ./.buildkite/scripts/install.sh
      ./.buildkite/scripts/run_tests.sh
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            TEST_ENGINE_TOKEN: TEST_ENGINE_TOKEN
      - docker-compose#v5.6.0:
          run: app
          config: "./docker-compose.test.yml"
          environment:
            - TEST_ENGINE_TOKEN
          retry:
            automatic:
              - limit: 2
                exit_status: 17
          propagate-environment: true
