agents:
  queue: linux-with-base

cache:
  paths:
    - ".elixir_ls"
    - "_build"
    - "deps"
  size: "20g"

steps:
  - label: ":elixir: build"
    key: build
    command: |
      ./.buildkite/scripts/install.sh
      ./.buildkite/scripts/run_tests.sh
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            TEST_ENGINE_TOKEN: TEST_ENGINE_TOKEN
