steps:
  - label: ":elixir: :docker: build"
    key: build
    plugins:
      - docker-compose#v5.6.0:
          build: app
          config: "./docker-compose.test.yml"
          retry:
            automatic:
              - limit: 2
                exit_status: 17

  - label: ":elixir: tests"
    key: test
    depends_on: build
    command:
      - .buildkite/scripts/run_tests.sh
    plugins:
      - docker-compose#v5.6.0:
          run: app
          config: "./docker-compose.test.yml"
          retry:
            automatic:
              - limit: 2
                exit_status: 17

  - label: ":elixir: :docker: build"
    key: release-build
    depends_on: test
    env:
      TAG: "latest"
    command: |
      # docker build --push "cloudcloud/episodical:${TAG}" .
