steps:
  - label: ":elixir: :docker: build"
    key: build
    plugins:
      - docker-compose#v5.6.0:
          build: app
          config: "./docker-compose.test.yml"
          retry:
            automatic:
              - limit: 2
                exit_status: 17
            propagate-environment: true

  - label: ":elixir: tests"
    key: test
    depends_on: build
    command:
      - .buildkite/scripts/run_tests.sh
    plugins:
      - cluster-secrets#v1.0.0:
          variables:
            TEST_ENGINE_TOKEN: TEST_ENGINE_TOKEN
      - docker-compose#v5.6.0:
          run: app
          config: "./docker-compose.test.yml"
          environment:
            - TEST_ENGINE_TOKEN
          retry:
            automatic:
              - limit: 2
                exit_status: 17
          propagate-environment: true

  - label: ":elixir: :docker: release"
    key: release-build
    depends_on: test
    command: .buildkite/scripts/build_and_push.sh
