services:
  database:
    image: postgres:17.4-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      dockerfile: Dockerfile.development
    depends_on:
      - database
    environment:
      PGHOST: database
